In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Carregar os dados (services,customers, contracts)
df_customers = pd.read_csv('datasets/churn_customers.csv')
df_contracts = pd.read_csv('datasets/churn_contracts.csv')
df_services = pd.read_csv('datasets/churn_services.csv')

### Analisando o Dataframe de Clientes

In [ ]:
# Analisando o dataframe de clientes
df_customers.head(5)

In [ ]:
df_customers.tail(5)

In [ ]:

df_customers.info()

### Analisando o dataframe de Serviços

In [10]:
df_services.head(5)

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [11]:
df_services.info(5)

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   PhoneService      7043 non-null   str
 2   MultipleLines     7043 non-null   str
 3   InternetService   7043 non-null   str
 4   OnlineSecurity    7043 non-null   str
 5   OnlineBackup      7043 non-null   str
 6   DeviceProtection  7043 non-null   str
 7   TechSupport       7043 non-null   str
 8   StreamingTV       7043 non-null   str
 9   StreamingMovies   7043 non-null   str
dtypes: str(10)
memory usage: 550.4 KB

### Analisando o dataset de Contratos

In [12]:
df_contracts.head(5)

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [13]:
df_contracts.tail(5)

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,24,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [14]:
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   str
 7   Churn             7043 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 440.3 KB

### Transformação de dados

In [17]:
# transformar colunas total charges de string para float
df_contracts.TotalCharges = pd.to_numeric(df_contracts.TotalCharges, errors='coerce')

In [19]:
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 440.3 KB

Após tranformar "TotalCharges" para float, a coluna passou a ter 11 valores ausentes (missing values)

In [20]:
# renomear colunas para facilitar a manipulação
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [23]:
df_customers.rename(columns={'SeniorCitizen': 'Above60yo'}, inplace=True)

In [24]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7043 non-null   str
 1   gender      7043 non-null   str
 2   Above60yo   7043 non-null   int64
 3   Partner     7043 non-null   str
 4   Dependents  7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

### Unificar os Dataframe: Contracts, Customers, Services

7043